name: Pipeline DevOps

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Login a Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Crear ACR si no existe y obtener credenciales
        run: |
          az acr create --name devopsvictor2026 --resource-group devops-proyecto-final-rg --sku Basic --admin-enabled true || true
          ACR_USERNAME=$(az acr credential show --name devopsvictor2026 --query username -o tsv)
          ACR_PASSWORD=$(az acr credential show --name devopsvictor2026 --query "passwords[0].value" -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      - name: Login a ACR
        uses: docker/login-action@v3
        with:
          registry: devopsvictor2026.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Construir y publicar imagen al ACR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: devopsvictor2026.azurecr.io/devops-proyecto-final:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Login a Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Import Resource Group
        run: terraform import azurerm_resource_group.rg /subscriptions/4acd162c-9d6e-41c1-aa72-3479a25b0c3a/resourceGroups/devops-proyecto-final-rg
        working-directory: terraform
        continue-on-error: true

      - name: Terraform Import ACR
        run: terraform import azurerm_container_registry.acr /subscriptions/4acd162c-9d6e-41c1-aa72-3479a25b0c3a/resourceGroups/devops-proyecto-final-rg/providers/Microsoft.ContainerRegistry/registries/devopsvictor2026
        working-directory: terraform
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform